ATTR_SMS_DATE = "sms_date"
ATTR_SMS_ID = "sms_id"
ATTR_SMS_FROM = "sms_from"
ATTR_SMS_TO = "sms_to"
ATTR_SMS_UNREAD = "sms_unread"
ATTR_SMS_DRAFT_GROUP_ID = "sms_draft_group_id"
ATTR_SMS_RCVD_ALL_CONCAT_SMS = "sms_rcvd_all_concat_sms"
ATTR_SMS_CONCAT_SMS_TOTAL = "sms_concat_sms_total"
ATTR_SMS_CONCAT_SMS_RCVD = "sms_concat_sms_rcvd"
ATTR_SMS_CLASS = "sms_class"
ATTR_SMS_PAYLOAD = "sms_payload"

CONF_ATTRIB_LIST = "enabled_attributes"

MODEM_STATE_ATTR = "modem_main_state"