zte_send_sms:
  fields:
    sms_to:
      required: true
      advanced: false
      example: "+351931234567"
      default: ""
    sms_payload:
      required: true
      advanced: false
      example: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
      default: ""

zte_sensors_state_control:
  fields:
    sensors_state:
      required: true
      advanced: false
      example: "sensor_state_running"
      default: "sensor_state_running"
